name: Build YouTube Downloader EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller yt-dlp pillow

    - name: Show project files
      run: dir

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --noconsole --onefile --icon=icon.ico yt_downloader.py

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: yt_downloader_exe
        path: dist/yt_downloader.exe
