name: Build Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller yt-dlp autopep8

      - name: Format code with autopep8
        run: autopep8 --in-place --aggressive --aggressive yt_downloader_upgraded.py

      - name: Download FFmpeg
        run: |
          Invoke-WebRequest -Uri https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-full.7z -OutFile ffmpeg.7z
          7z x ffmpeg.7z -o"ffmpeg"
          Copy-Item -Path "ffmpeg\ffmpeg-git-*\bin\ffmpeg.exe" -Destination "."
          Copy-Item -Path "ffmpeg\ffmpeg-git-*\bin\ffplay.exe" -Destination "."
          Copy-Item -Path "ffmpeg\ffmpeg-git-*\bin\ffprobe.exe" -Destination "."
          Remove-Item -Path ffmpeg.7z -Force
          Remove-Item -Path ffmpeg -Recurse -Force

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --windowed --icon=icon.ico --name="YouTube Downloader" yt_downloader_upgraded.py

      - name: Upload executable
        uses: actions/upload-artifact@v4  # 这里是关键修改，升级到 v4
        with:
          name: YouTube Downloader
          path: dist/YouTube Downloader.exe
